# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a7d02b9b2d3e32d61163503c8191cd5c5557a944dc1d5c32a33effd4e7f134c8833c22ecb48dd7e4693dbaa0555014b17ff8079b655b5d3ae71cc8c00bf5b74

test:
  secret_key_base: b2ed3daea2d8e80268e2548be3ff79a315332b5efdbe5d5c280a32f0a07e3a42d357012597a4c88cf1fe626d08089d0bda91b317d29704e05ab45795701f9b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
